/* ============== CREACIÓN DE BASE DE DATOS & CONFIGURACION DE CARACTERES E IDIOMA NATIVO============= */
CREATE DATABASE IF NOT EXISTS COLEGIO_AMERICANO CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish2_ci;

/* ================ SELECCIÓN DE BASE DE DATOS ================== */
USE COLEGIO_AMERICANO;

/* CREATE USER 'admincolegio'@'localhost' IDENTIFIED BY 'password';
SELECT Host,User from mysql.user; */

/* ================ CREACION DE TABLAS =================*/

CREATE TABLE ALUMNOS(
	ID_ALUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRES VARCHAR(40),
	APELLIDO_P VARCHAR(40),
    APELLIDO_M VARCHAR(40),
	RUT VARCHAR(13) UNIQUE NOT NULL,
	FECHA_NAC DATE,
    CORREO VARCHAR(40),
	DIRECCION VARCHAR(40),
	COMUNA VARCHAR(40),
    APOD_TITULAR INT,
    APOD_SUPLENTE INT,
    FK_ID_CURSO INT
)
COMMENT 'CREACION DE TABLAS PARA ALUMNOS';

CREATE TABLE APODERADOS(
	ID_APOD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRES VARCHAR(40),
    APELLIDO_P VARCHAR(40),
    APELLIDO_M VARCHAR(40),
    RUT VARCHAR(13) UNIQUE NOT NULL,
    TELEFONO1 INT,
	TELEFONO2 INT,
    DIRECCION VARCHAR(100),
    COMUNA VARCHAR(40)
)
COMMENT 'CREACION DE TABLAS PARA APODERADOS';

CREATE TABLE CURSOS(
	ID_CURSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUM_CURSO VARCHAR(3) UNIQUE NOT NULL
)
COMMENT 'CREACION DE TABLAS PARA CURSOS';

CREATE TABLE RETIROS(
	ID_RETIRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA DATETIME,
    FK_ID_APOD INT,
    FK_ID_ALUM INT,
    FK_ID_CURSO INT
)
COMMENT 'CREACION DE TABLAS PARA RETIROS';

/* ================= ALTERS ==================*/
 /*===================== FOREIGN KEYS ===================== */
 
ALTER TABLE ALUMNOS
ADD CONSTRAINT FOREIGN KEY (APOD_TITULAR) REFERENCES APODERADOS(ID_APOD);

ALTER TABLE ALUMNOS
ADD CONSTRAINT FOREIGN KEY (APOD_SUPLENTE) REFERENCES APODERADOS(ID_APOD);
 
ALTER TABLE RETIROS 
ADD CONSTRAINT FOREIGN KEY (FK_ID_CURSO) REFERENCES CURSOS(ID_CURSO) ;

ALTER TABLE RETIROS 
ADD CONSTRAINT FOREIGN KEY (FK_ID_APOD) REFERENCES APODERADOS(ID_APOD) ;

ALTER TABLE RETIROS 
ADD CONSTRAINT FOREIGN KEY (FK_ID_ALUM) REFERENCES ALUMNOS(ID_ALUM) ;

ALTER TABLE ALUMNOS
ADD CONSTRAINT FOREIGN KEY (FK_ID_CURSO) REFERENCES CURSOS(ID_CURSO);

 /*===================== INSERT ===================== */
 
 INSERT INTO CURSOS(NUM_CURSO)
 VALUES	('1A'),('2A'),('3A'),('4A'),('5A'),('6A'),('7A'),('8A'),('1B'),('2B'),('3B'),('4B'),('5B'),('6B'),('7B'),('8B');
 
 