/* CREACION DE PROCEDIMIENTOS ALMACENADOS ( INSERT , UPDATE , SELECT ) */

/* ========== AGREGAR NUEVO ALUMNO ============*/

DELIMITER $$
CREATE PROCEDURE SP_NUEVOALUMNO(
	IN _NOMBRES VARCHAR(40),
    IN _APELLIDO_P VARCHAR(40),
    IN _APELLIDO_M VARCHAR(40),
    IN _RUT VARCHAR(13),
    IN _FECHA_NAC DATE,
    IN _DIRECCION VARCHAR(40),
    IN _COMUNA VARCHAR(40),
    IN _FK_ID_CURSO INT
)
BEGIN
	DECLARE _ID_ALUM INT; 
    DECLARE _CORREO VARCHAR(40);
    SELECT MAX(ID_ALUM)+1 
    INTO _ID_ALUM 
    FROM ALUMNOS;
    SELECT LOWER(CONCAT(LEFT(_NOMBRES,1),_APELLIDO_P,CONCAT(LEFT(_APELLIDO_M,1)),'@colegioamericano.cl')) 
    INTO _CORREO;
	INSERT INTO ALUMNOS (ID_ALUM,NOMBRES, APELLIDO_P,APELLIDO_M, RUT, FECHA_NAC,CORREO,DIRECCION,COMUNA,FK_ID_CURSO)
	VALUES (_ID_ALUM,_NOMBRES, _APELLIDO_P,_APELLIDO_M, _RUT, _FECHA_NAC,_CORREO,_DIRECCION,_COMUNA,_FK_ID_CURSO);
END
$$
