/* CREACION DE PROCEDIMIENTOS ALMACENADOS ( INSERT , UPDATE , SELECT ) */

/* ========== AGREGAR NUEVO APODERADO =============*/

DELIMITER $$
CREATE PROCEDURE SP_NUEVOAPODERADO(
    IN _NOMBRES VARCHAR(40),
    IN _APELLIDO_P VARCHAR(40),
    IN _APELLIDO_M VARCHAR(40),
    IN _RUT VARCHAR(13),
    IN _TELEFONO1 INT,
    IN _TELEFONO2 INT,
    IN _DIRECCION VARCHAR(100),
    IN _COMUNA VARCHAR(40)
)
BEGIN
	DECLARE _ID_APOD INT; 
    SELECT MAX(ID_APOD)+1 
    INTO _ID_APOD 
    FROM APODERADOS;
	INSERT INTO APODERADOS(ID_APOD,NOMBRES,APELLIDO_P,APELLIDO_M,RUT,TELEFONO1,TELEFONO2,DIRECCION,COMUNA)
    VALUES (_ID_APOD,_NOMBRES,_APELLIDO_P,_APELLIDO_M,_RUT,_TELEFONO1,_TELEFONO2,_DIRECCION,_COMUNA);
END
$$
