/* CREACION DE PROCEDIMIENTOS ALMACENADOS ( INSERT , UPDATE , SELECT ) */

/* ===== INGRESAR NUEVO RETIRO=====*/

DELIMITER $$ 
CREATE PROCEDURE SP_RETIRO(  
    IN _FECHA DATETIME,
    IN _FK_ID_ALUM INT,
    IN _FK_ID_CURSO INT,
    IN _FK_ID_APOD INT
)
BEGIN
		DECLARE _ID_RETIRO INT;
		SELECT MAX(ID_RETIRO)+1
        INTO _ID_RETIRO
        FROM RETIROS;
		INSERT INTO RETIROS(ID_RETIRO,FECHA,FK_ID_APOD,FK_ID_ALUM,FK_ID_CURSO)
        VALUES(_ID_RETIRO,_FECHA,_FK_ID_APOD,_FK_ID_ALUM,_FK_ID_CURSO);
END
$$        
