/* CREACION DE PROCEDIMIENTOS ALMACENADOS ( INSERT , UPDATE , SELECT ) */

/*==========CONSULTA RETIRO DE ALUMNOS X CURSO ================  */

DELIMITER $$
CREATE PROCEDURE SP_RETIROXCURSO(
	IN _FK_ID_CURSO INT
)
BEGIN
		SELECT 	DATE_FORMAT(R.FECHA,'%d-%m-%Y') AS 'Fecha', -- EXTRAEMOS SOLO DIA/MES/AÑO
        DATE_FORMAT(R.FECHA,'%H:%i') AS 'Hora',		-- EXTRAEMOS SOLO HORAS Y MINUTOS
		/*R.FECHA AS 'Fecha / Hora',*/
        C.NUM_CURSO AS 'Curso',
        A.NOMBRES AS 'Nombres Alumno',
		CONCAT(A.APELLIDO_P,' ',A.APELLIDO_M) AS 'Apellidos Alumno',
        A.RUT AS 'Rut Alumno',
		CONCAT(B.NOMBRES,' ',B.APELLIDO_P,' ',B.APELLIDO_M) AS 'Retirado por',
		B.RUT AS 'Rut Apoderado',
        B.TELEFONO1 AS 'Telefono Contacto'
		FROM RETIROS R
		LEFT JOIN ALUMNOS A
		ON R.FK_ID_ALUM = A.ID_ALUM
		LEFT JOIN APODERADOS B
		ON R.FK_ID_APOD = B.ID_APOD
        LEFT JOIN CURSOS C
        ON R.FK_ID_CURSO = C.ID_CURSO
        WHERE R.FK_ID_CURSO = _FK_ID_CURSO;
END
$$
